- name: install nginx
  package:
    name: nginx
    state: present

- name: change perms
  file:
    path: /var/lib/nginx
    owner: www-data
    group: www-data
    mode: '0755'
  when: ansible_distribution == 'Ubuntu'

- name: add conf file
  copy:
    src: files/default.conf
    dest: /etc/nginx/sites-enabled/default
    owner: www-data
    group: www-data
    mode: '0755'
  when: ansible_distribution == 'Ubuntu'


- name: add conf file
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
    mode: '0755'
  when: ansible_distribution == 'CentOS'

- name: add /html dir
  file:
    state: directory
    path: /html
    owner: www-data
    group: www-data
    mode: '0755'
  when: ansible_distribution == 'Ubuntu'

- name: add /html dir
  file:
    state: directory
    path: /html
    owner: nginx
    group: nginx
    mode: '0755'
  when: ansible_distribution == 'CentOS'
