- name: score 100 on this test
  hosts: localhost
  become: yes
  tasks:
    - name: install nginx
      package:
        name: nginx
        state: present

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_distribution == 'Ubuntu'

    - name: start nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
        daemon_reload: yes
      when: ansible_distribution == 'CentOS'
