- name: score 100 on this test
  hosts: localhost
  become: yes
  tasks:
    - name: install nginx
      package:
        name: nginx
        state: present

    - name: change perms
      file:
        path: /var/lib/nginx
        owner: www-data
        group: www-data
        mode: '0755'

